<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Livro</title>
</head>

<body>
    <h1>Criar Livro</h1>

    <form action="/livros/store" method="POST">
        <table>
            <tr>
                <td>Título:</td>
                <td><input type="text" name="titulo"/></td>
            </tr>

            <tr>
                <td>Autor:</td>
                <td><input type="text" name="autor"/></td>
            </tr>

            <tr>
                <td>ISBN:</td>
                <td><input type="text" name="isbn"/></td>
            </tr>

            <tr>
                <td>Editora:</td>
                <td><input type="text" name="editora"/></td>
            </tr>

            <tr>
                <td>Ano de Publicação:</td>
                <td><input type="number" name="anoPublicacao"/></td>
            </tr>

            <tr>
                <td>Sinopse:</td>
                <td><textarea name="sinopse" cols="30" rows="10"></textarea></td>
            </tr>

            <tr>
                <td>Número de Páginas:</td>
                <td><input type="number" name="numeroPaginas"/></td>
            </tr>

            <tr align="center">
                <td colspan="2"><input type="submit" value="Criar"/></td>
            </tr>

            <tr align="center">
                <td colspan="2">
                    <a href="/livros" style="display: inline">&#9664;&nbsp;Voltar</a>
                </td>
            </tr>
        </table>
    </form>
</body>

</html>