<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Novo Autor</title>
</head>

<body>
    <h1>Cadastrar Novo Autor</h1>
    <form action="/autores/store" method="POST">
        <table>
            <tr>
                <td>Nome:</td>
                <td><input type="text" name="nome" required/></td>
            </tr>
            <tr>
                <td>Bio:</td>
                <td><textarea name="bio" cols="30" rows="10"></textarea></td>
            </tr>
            <tr align="center">
                <td colspan="2"><input type="submit" value="Criar"/></td>
            </tr>
            <tr align="center">
                <td colspan="2"><a href="/autores" style="display: inline">&#9664;&nbsp;Voltar</a></td>
            </tr>
        </table>
    </form>
</body>

</html>
