<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nova Resenha</title>
</head>

<body>
    <h1>Cadastrar Nova Resenha</h1>
    <form action="/resenhas/store" method="POST">
        <table>
            <tr>
                <td>Texto:</td>
                <td><textarea name="texto" cols="30" rows="10" required></textarea></td>
            </tr>
            <tr align="center">
                <td colspan="2"><input type="submit" value="Criar"/></td>
            </tr>
            <tr align="center">
                <td colspan="2"><a href="/resenhas" style="display: inline">&#9664;&nbsp;Voltar</a></td>
            </tr>
        </table>
    </form>
</body>

</html>
